"""Init base de datos con tablas HR

Revision ID: 038af17dce13
Revises: 
Create Date: 2026-06-22 03:51:24.000810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038af17dce13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=False),
    sa.Column('plan_suscripcion', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('empresa_id'),
    sa.UniqueConstraint('ruc')
    )
    op.create_index(op.f('ix_empresas_empresa_id'), 'empresas', ['empresa_id'], unique=False)
    op.create_table('departamentos',
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['departamentos.departamento_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('departamento_id')
    )
    op.create_index(op.f('ix_departamentos_departamento_id'), 'departamentos', ['departamento_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_usuarios_usuario_id'), 'usuarios', ['usuario_id'], unique=False)
    op.create_table('cargos',
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.departamento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cargo_id')
    )
    op.create_index(op.f('ix_cargos_cargo_id'), 'cargos', ['cargo_id'], unique=False)
    op.create_table('eventos_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('fecha_evento', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_auditoria_id'), 'eventos_auditoria', ['id'], unique=False)
    op.create_table('nominas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('total_ingresos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_descuentos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_neto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_aprobacion', sa.TIMESTAMP(), nullable=True),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuarios.usuario_id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nominas_id'), 'nominas', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('notificacion_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notificacion_id')
    )
    op.create_index(op.f('ix_notificaciones_notificacion_id'), 'notificaciones', ['notificacion_id'], unique=False)
    op.create_table('detalles_nomina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomina_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('horas_contrato_mes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('horas_trabajadas', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('horas_ausentes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sueldo_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('haberes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descuento_inasistencias', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_ingresos_brutos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo_pension', sa.String(length=10), nullable=True),
    sa.Column('aporte_pension', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('impuesto_renta_5ta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descuentos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sueldo_neto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('aporte_empleador_essalud', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['nomina_id'], ['nominas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_nomina_id'), 'detalles_nomina', ['id'], unique=False)
    op.create_table('empleados',
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('tipo_pension', sa.String(length=10), nullable=True),
    sa.Column('porcentaje_afp', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.cargo_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.departamento_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('empleado_id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_empleados_empleado_id'), 'empleados', ['empleado_id'], unique=False)
    op.create_table('historiales_aprobacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomina_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado_anterior', sa.String(length=50), nullable=False),
    sa.Column('estado_nuevo', sa.String(length=50), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('fecha_cambio', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['nomina_id'], ['nominas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historiales_aprobacion_id'), 'historiales_aprobacion', ['id'], unique=False)
    op.create_table('contratos',
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=50), nullable=False),
    sa.Column('sueldo_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('horas_contrato_mes', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.empleado_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contrato_id')
    )
    op.create_index(op.f('ix_contratos_contrato_id'), 'contratos', ['contrato_id'], unique=False)
    op.create_table('inasistencias',
    sa.Column('inasistencia_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('horas_ausentes', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.empleado_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('inasistencia_id')
    )
    op.create_index(op.f('ix_inasistencias_inasistencia_id'), 'inasistencias', ['inasistencia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inasistencias_inasistencia_id'), table_name='inasistencias')
    op.drop_table('inasistencias')
    op.drop_index(op.f('ix_contratos_contrato_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_historiales_aprobacion_id'), table_name='historiales_aprobacion')
    op.drop_table('historiales_aprobacion')
    op.drop_index(op.f('ix_empleados_empleado_id'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_index(op.f('ix_detalles_nomina_id'), table_name='detalles_nomina')
    op.drop_table('detalles_nomina')
    op.drop_index(op.f('ix_notificaciones_notificacion_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_nominas_id'), table_name='nominas')
    op.drop_table('nominas')
    op.drop_index(op.f('ix_eventos_auditoria_id'), table_name='eventos_auditoria')
    op.drop_table('eventos_auditoria')
    op.drop_index(op.f('ix_cargos_cargo_id'), table_name='cargos')
    op.drop_table('cargos')
    op.drop_index(op.f('ix_usuarios_usuario_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_departamentos_departamento_id'), table_name='departamentos')
    op.drop_table('departamentos')
    op.drop_index(op.f('ix_empresas_empresa_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
