"""fase5_desempeno_kardex

Revision ID: 2c4c9db827c3
Revises: a7d1ab1ea6f3
Create Date: 2026-07-07 01:33:07.915323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4c9db827c3'
down_revision: Union[str, Sequence[str], None] = 'a7d1ab1ea6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluaciones_desempeno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('puntualidad', sa.Integer(), nullable=False),
    sa.Column('calidad_trabajo', sa.Integer(), nullable=False),
    sa.Column('trabajo_equipo', sa.Integer(), nullable=False),
    sa.Column('iniciativa', sa.Integer(), nullable=False),
    sa.Column('puntaje_promedio', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('evaluado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_evaluacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.empleado_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluado_por'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluaciones_desempeno_empleado_id'), 'evaluaciones_desempeno', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_evaluaciones_desempeno_empresa_id'), 'evaluaciones_desempeno', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_evaluaciones_desempeno_id'), 'evaluaciones_desempeno', ['id'], unique=False)
    op.create_index(op.f('ix_evaluaciones_desempeno_is_deleted'), 'evaluaciones_desempeno', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_evaluaciones_desempeno_periodo'), 'evaluaciones_desempeno', ['periodo'], unique=False)
    op.create_table('incidencias_disciplinarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('dias_suspension', sa.Integer(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.empleado_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidencias_disciplinarias_empleado_id'), 'incidencias_disciplinarias', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_incidencias_disciplinarias_empresa_id'), 'incidencias_disciplinarias', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_incidencias_disciplinarias_id'), 'incidencias_disciplinarias', ['id'], unique=False)
    op.create_index(op.f('ix_incidencias_disciplinarias_is_deleted'), 'incidencias_disciplinarias', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidencias_disciplinarias_is_deleted'), table_name='incidencias_disciplinarias')
    op.drop_index(op.f('ix_incidencias_disciplinarias_id'), table_name='incidencias_disciplinarias')
    op.drop_index(op.f('ix_incidencias_disciplinarias_empresa_id'), table_name='incidencias_disciplinarias')
    op.drop_index(op.f('ix_incidencias_disciplinarias_empleado_id'), table_name='incidencias_disciplinarias')
    op.drop_table('incidencias_disciplinarias')
    op.drop_index(op.f('ix_evaluaciones_desempeno_periodo'), table_name='evaluaciones_desempeno')
    op.drop_index(op.f('ix_evaluaciones_desempeno_is_deleted'), table_name='evaluaciones_desempeno')
    op.drop_index(op.f('ix_evaluaciones_desempeno_id'), table_name='evaluaciones_desempeno')
    op.drop_index(op.f('ix_evaluaciones_desempeno_empresa_id'), table_name='evaluaciones_desempeno')
    op.drop_index(op.f('ix_evaluaciones_desempeno_empleado_id'), table_name='evaluaciones_desempeno')
    op.drop_table('evaluaciones_desempeno')
    # ### end Alembic commands ###
