"""fase5_conceptos_variables

Revision ID: 86855fb56447
Revises: ab171959e8b4
Create Date: 2026-07-07 01:09:31.419374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86855fb56447'
down_revision: Union[str, Sequence[str], None] = 'ab171959e8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conceptos_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cuotas', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.empleado_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conceptos_variables_empleado_id'), 'conceptos_variables', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_conceptos_variables_empresa_id'), 'conceptos_variables', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_conceptos_variables_id'), 'conceptos_variables', ['id'], unique=False)
    op.create_index(op.f('ix_conceptos_variables_is_deleted'), 'conceptos_variables', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_conceptos_variables_periodo'), 'conceptos_variables', ['periodo'], unique=False)
    op.add_column('detalles_nomina', sa.Column('descuento_prestamos', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalles_nomina', 'descuento_prestamos')
    op.drop_index(op.f('ix_conceptos_variables_periodo'), table_name='conceptos_variables')
    op.drop_index(op.f('ix_conceptos_variables_is_deleted'), table_name='conceptos_variables')
    op.drop_index(op.f('ix_conceptos_variables_id'), table_name='conceptos_variables')
    op.drop_index(op.f('ix_conceptos_variables_empresa_id'), table_name='conceptos_variables')
    op.drop_index(op.f('ix_conceptos_variables_empleado_id'), table_name='conceptos_variables')
    op.drop_table('conceptos_variables')
    # ### end Alembic commands ###
