"""fase5_beneficios_sociales

Revision ID: 99c0736bd7f1
Revises: d6c30787b4e4
Create Date: 2026-07-07 00:52:08.658472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c0736bd7f1'
down_revision: Union[str, Sequence[str], None] = 'd6c30787b4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficios_sociales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('meses_computados', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('remuneracion_computable', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_bruto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonificacion_extraordinaria', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('aporte_pension', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_neto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_calculo', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_pago', sa.TIMESTAMP(), nullable=True),
    sa.Column('calculado_por', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['calculado_por'], ['usuarios.usuario_id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.empleado_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficios_sociales_empleado_id'), 'beneficios_sociales', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_beneficios_sociales_empresa_id'), 'beneficios_sociales', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_beneficios_sociales_id'), 'beneficios_sociales', ['id'], unique=False)
    op.create_index(op.f('ix_beneficios_sociales_is_deleted'), 'beneficios_sociales', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_beneficios_sociales_periodo'), 'beneficios_sociales', ['periodo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beneficios_sociales_periodo'), table_name='beneficios_sociales')
    op.drop_index(op.f('ix_beneficios_sociales_is_deleted'), table_name='beneficios_sociales')
    op.drop_index(op.f('ix_beneficios_sociales_id'), table_name='beneficios_sociales')
    op.drop_index(op.f('ix_beneficios_sociales_empresa_id'), table_name='beneficios_sociales')
    op.drop_index(op.f('ix_beneficios_sociales_empleado_id'), table_name='beneficios_sociales')
    op.drop_table('beneficios_sociales')
    # ### end Alembic commands ###
