"""fase5_aprobacion_sobretiempo

Revision ID: a7d1ab1ea6f3
Revises: e8b8c6ac766d
Create Date: 2026-07-07 01:26:21.361802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d1ab1ea6f3'
down_revision: Union[str, Sequence[str], None] = 'e8b8c6ac766d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horas_periodo', sa.Column('estado', sa.String(length=15), nullable=False, server_default='Pendiente'))
    op.add_column('horas_periodo', sa.Column('aprobado_por', sa.Integer(), nullable=True))
    op.add_column('horas_periodo', sa.Column('fecha_aprobacion', sa.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'horas_periodo', 'usuarios', ['aprobado_por'], ['usuario_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'horas_periodo', type_='foreignkey')
    op.drop_column('horas_periodo', 'fecha_aprobacion')
    op.drop_column('horas_periodo', 'aprobado_por')
    op.drop_column('horas_periodo', 'estado')
    # ### end Alembic commands ###
