"""fase5_liquidaciones

Revision ID: ab171959e8b4
Revises: 99c0736bd7f1
Create Date: 2026-07-07 01:01:24.147542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab171959e8b4'
down_revision: Union[str, Sequence[str], None] = '99c0736bd7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquidaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('fecha_cese', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=30), nullable=False),
    sa.Column('dias_vacaciones_truncas', sa.Integer(), nullable=False),
    sa.Column('monto_vacaciones_truncas', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meses_gratificacion_trunca', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('monto_gratificacion_trunca', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonificacion_extraordinaria', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meses_cts_trunca', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('monto_cts_trunca', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_calculo', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_pago', sa.TIMESTAMP(), nullable=True),
    sa.Column('calculado_por', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['calculado_por'], ['usuarios.usuario_id'], ),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.empleado_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidaciones_empleado_id'), 'liquidaciones', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_liquidaciones_empresa_id'), 'liquidaciones', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_liquidaciones_id'), 'liquidaciones', ['id'], unique=False)
    op.create_index(op.f('ix_liquidaciones_is_deleted'), 'liquidaciones', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liquidaciones_is_deleted'), table_name='liquidaciones')
    op.drop_index(op.f('ix_liquidaciones_id'), table_name='liquidaciones')
    op.drop_index(op.f('ix_liquidaciones_empresa_id'), table_name='liquidaciones')
    op.drop_index(op.f('ix_liquidaciones_empleado_id'), table_name='liquidaciones')
    op.drop_table('liquidaciones')
    # ### end Alembic commands ###
