"""jerarquia_en_cargos

Revision ID: bcc1487d292f
Revises: 4ad8a3b02eab
Create Date: 2026-06-22 08:28:43.051786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc1487d292f'
down_revision: Union[str, Sequence[str], None] = '4ad8a3b02eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cargos', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cargos', 'cargos', ['parent_id'], ['cargo_id'], ondelete='SET NULL')
    op.drop_constraint(op.f('departamentos_parent_id_fkey'), 'departamentos', type_='foreignkey')
    op.drop_column('departamentos', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departamentos', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('departamentos_parent_id_fkey'), 'departamentos', 'departamentos', ['parent_id'], ['departamento_id'], ondelete='SET NULL')
    op.drop_constraint(None, 'cargos', type_='foreignkey')
    op.drop_column('cargos', 'parent_id')
    # ### end Alembic commands ###
