"""agregar_tabla_pagos

Revision ID: bf73f84f8107
Revises: bcc1487d292f
Create Date: 2026-07-04 05:11:26.839285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf73f84f8107'
down_revision: Union[str, Sequence[str], None] = 'bcc1487d292f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('num_empleados', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=30), nullable=False),
    sa.Column('tarjeta_ultimos4', sa.String(length=4), nullable=True),
    sa.Column('referencia', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_pago', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pago_id'),
    sa.UniqueConstraint('referencia')
    )
    op.create_index(op.f('ix_pagos_pago_id'), 'pagos', ['pago_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_pago_id'), table_name='pagos')
    op.drop_table('pagos')
    # ### end Alembic commands ###
