"""fase5_vacaciones

Revision ID: d6c30787b4e4
Revises: f3a0kiosco
Create Date: 2026-07-07 00:32:15.220351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c30787b4e4'
down_revision: Union[str, Sequence[str], None] = 'f3a0kiosco'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_vacaciones',
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias_solicitados', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('resuelto_por', sa.Integer(), nullable=True),
    sa.Column('fecha_resolucion', sa.TIMESTAMP(), nullable=True),
    sa.Column('fecha_solicitud', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.empleado_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resuelto_por'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('solicitud_id')
    )
    op.create_index(op.f('ix_solicitudes_vacaciones_empleado_id'), 'solicitudes_vacaciones', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_vacaciones_empresa_id'), 'solicitudes_vacaciones', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_vacaciones_is_deleted'), 'solicitudes_vacaciones', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_solicitudes_vacaciones_solicitud_id'), 'solicitudes_vacaciones', ['solicitud_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_vacaciones_solicitud_id'), table_name='solicitudes_vacaciones')
    op.drop_index(op.f('ix_solicitudes_vacaciones_is_deleted'), table_name='solicitudes_vacaciones')
    op.drop_index(op.f('ix_solicitudes_vacaciones_empresa_id'), table_name='solicitudes_vacaciones')
    op.drop_index(op.f('ix_solicitudes_vacaciones_empleado_id'), table_name='solicitudes_vacaciones')
    op.drop_table('solicitudes_vacaciones')
    # ### end Alembic commands ###
