"""fase5_permisos_autogestion

Revision ID: e8b8c6ac766d
Revises: 86855fb56447
Create Date: 2026-07-07 01:17:45.003203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b8c6ac766d'
down_revision: Union[str, Sequence[str], None] = '86855fb56447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_permiso',
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horas', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('documento_path', sa.String(length=300), nullable=True),
    sa.Column('documento_nombre', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('inasistencia_id', sa.Integer(), nullable=True),
    sa.Column('resuelto_por', sa.Integer(), nullable=True),
    sa.Column('fecha_resolucion', sa.TIMESTAMP(), nullable=True),
    sa.Column('fecha_solicitud', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.empleado_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inasistencia_id'], ['inasistencias.inasistencia_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resuelto_por'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('solicitud_id')
    )
    op.create_index(op.f('ix_solicitudes_permiso_empleado_id'), 'solicitudes_permiso', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_permiso_empresa_id'), 'solicitudes_permiso', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_permiso_is_deleted'), 'solicitudes_permiso', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_solicitudes_permiso_solicitud_id'), 'solicitudes_permiso', ['solicitud_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_permiso_solicitud_id'), table_name='solicitudes_permiso')
    op.drop_index(op.f('ix_solicitudes_permiso_is_deleted'), table_name='solicitudes_permiso')
    op.drop_index(op.f('ix_solicitudes_permiso_empresa_id'), table_name='solicitudes_permiso')
    op.drop_index(op.f('ix_solicitudes_permiso_empleado_id'), table_name='solicitudes_permiso')
    op.drop_table('solicitudes_permiso')
    # ### end Alembic commands ###
